### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by danez** [tleunen/find-babel-config#30]
We are thinking about using this package in babel-loader (see babel/babel-loader#456). The main difference between the implementations in this package and `babel-loader` right now is that babel-loader is heavily caching fs-calls.
Forcing a cache in this package is probably not a good idea, as the usecases could vary. But maybe it would be nice to have an option to somehow enable caching. This could be useful if one is not expecting the filesystem to change while running this package, like `babel-loader` is.
Maybe the user could supply an object where the cache is stored in, so that it can also be invalidated from the outside.

```js
const find = require('find-babel-config');
const cache = {};

find.sync(directory, null, cache);

// invalidate 
cache = {};

// again
find.sync(directory, null, cache);
```

Would you be open for a PR to add this?

**Comment by tleunen** [comment]
Oh yes, I do believe having a cache would be great. 
But as you mentioned, it shouldn't probably live inside the package, unless we keep some meta data attached to it like last modified date. In that case we would still need to do a `fs.stat` or sth similar to get the new info, but it wouldn't be as fast.

Letting the end user provide the cache object would definitely work though. But if we're adding more "options", I'd probably go for an object options instead of adding more arguments.

Do you think we could have a default cache? I doubt the file will/could change during execution in most cases, but you have more experience in Babel than me so I might be wrong...

```js
const { file, config, cache } = find.sync(directory, {
  depth: Infinity,
  cache: {}
});
```

But I'd definitely be open to add this feature. Thanks for suggesting it.

**Comment by danez** [comment]
Grouping them in an option object sounds reasonable.

I'm not sure about a default cache, but you are probably correct, that in most cases people wont see any problems.

How do you invalidate the default cache? Or we don't allow to invalidate and instead if people want to invalidate the have to provide their own caching object? Or expose a separate function like `resetCache()`? Though that seems to get to complex.

Maybe:

- If `cache` not provided (`undefined`) the package will cache stuff internally, but no way to invalidate in this case.
- If `cache` is `null` cache is disabled.
- If `cache` is an object then use it for caching and invalidating can be done simply by modifying the object yourself or simply provide a new one.

**Comment by tleunen** [comment]
In my previous code, the only way to invalidate the cache would indeed to make a new call and specifying a new cache object.

I think your suggestions are all valid. Although I'd tend to go with `cache: false` instead of `null` 😉

**Comment by danez** [comment]
We had to fix it in a different way in babel-loader, so feel free to close this.
